### ISSUE TITLE
Αποτυχία δημοσίευσης μηνύματος!

### ISSUE THREAD

**Issue by Hall900** [librenet/librenet.gr#13]
Καλησπέρα

Κάθε φορά που προσπαθώ να γράψω σχόλιο σε κάποιο post παίρνω αυτό το μήνυμα "Αποτυχία δημοσίευσης μηνύματος!" και φυσικά δεν γίνεται δεκτό το αίτημα.

                                                                                                                        Ευχαριστώ

**Comment by comzeradd** [comment]
Ευχαριστούμε για το report. Κάνουμε κάποιες εργασίες αναβάθμισης και κάποιες λειτουργίες του site είναι σε κατάσταση read-only. Θα ενημερώσουμε μόλις ολοκληρωθούν οι εργασίες.

**Comment by comzeradd** [comment]
Σιγά σιγά αποκαθίστανται οι λειτουργίες :) Τα σχόλια πρέπει να δουλεύουν κανονικά τώρα.
