### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by andre2000** [librenet/librenet.gr#9]
hi!

Some diaspora images are broken on librenet.gr, they're ok on other pods. I can see only icon of broken image.

I'm not sure how to give you examples, because https links are refered to my librenet.gr account, right?

**Comment by comzeradd** [comment]
You mean images people post or diaspora images?

**Comment by andre2000** [comment]
People post

**Comment by andre2000** [comment]
I've just sent the example screenshot on your e-mail address.

**Comment by comzeradd** [comment]
It seems limited to this specific user. I tried some other contacts, including [me](https://librenet.gr/people/d95d088043de0132801b7b2db0e68946/photos), and photos are properly displayed.

@axilleas Do you think it's a camo issue on our side or it's the user's pod?

**Comment by andre2000** [comment]
It's not only this user problem. I've choosen "inspect element" on broken image icon and https librenet.gr link with camo showed up. I'll try to sent you more examples.

**Comment by axilleas** [comment]
Yeah, I have noticed this in quite a few images in our pod. I will ask the guys in the irc `diaspora-dev`.

**Comment by axilleas** [comment]
It seems to be an issue with users on joindiaspora.com only:

## Not working (on joindiaspora.com)

* https://librenet.gr/people/f4aefef1c70c5a0a/photos
* https://librenet.gr/people/3e98d525f82852a2/photos

## Working (not on joindiaspora.com)

* https://librenet.gr/people/4ce5b01a9e3a1b18d700000a/photos
* https://librenet.gr/people/a3915bf02dfc013359ee7e8f7b917a82/photos

**Comment by axilleas** [comment]
Fixed with help from Fla in the irc. Reading https://wiki.diasporafoundation.org/Camo#Recommended_Camo_settings we were missing the mime types. For now I edited the file by hand.
